<a href="https://colab.research.google.com/github/AvinashKushwah/cs6910_assignment1/blob/main/Question3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
import numpy as np


# Load the Fashion-MNIST dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
print(y_train.shape)
# Define the class names
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
               

(60000,)


In [22]:
# Normalize the image pixel intesity within a range of 0-1
x_trainFlat = x_train.reshape(len(x_train),784).astype('float32')/255
print(x_trainFlat.shape)
x_testFlat = x_test.reshape(len(x_test),784).astype('float32')/255
print(x_testFlat.shape)



(60000, 784)
(10000, 784)


In [23]:
# Activation Function

def sigmoid(x):
    """
    Compute the sigmoid of x in a numerically stable way.
    """
    # Avoid overflow by clipping large values
    x = np.clip(x, -500, 500)
    return 1 / (1 + np.exp(-x))


# def sigmoid(x):# limit the range of x to avoid overflow
#   return 1 / (1 + np.exp(-x))
 
def sigmoid_diff(x):
  return (1 - sigmoid(x)) * sigmoid(x)

def ReLU(x):
    return np.maximum(x, 0)

def ReLU_deriv(x):
    return x > 0

def tanh(x):
    return np.tanh(x)

def tanh_deriv(x):
    return 1 - np.square(np.tanh(x))

def softmax1(Z):
  A = np.exp(Z) / (sum(np.exp(Z)) + 1e-9)
  return A
  


In [24]:
layers = int(input("enter number of Hidden layers:"))
layers = int(layers)

enter number of Hidden layers:2


In [25]:
# layers = input("enter number of Hidden layers:")
# layers = int(layers)
# numberOfNeurons =[]               # number of neurons at each Hidden Layer
# W = []                            #store the Weight matrix at each layer
# b = []                            #store the bias vector at each layer


# for i in range(layers):                       
#   randomNumber = np.random.randint(4,10)
#   numberOfNeurons.append(randomNumber)
#   if( i== 0):
#     w_temp =np.random.rand(randomNumber,784)
#     b_temp = np.random.rand(randomNumber)
#     W.append(w_temp)
#     b.append(b_temp)
#   else:
#     w_temp = np.random.rand(numberOfNeurons[i],numberOfNeurons[i-1])
#     b_temp = np.random.rand(numberOfNeurons[i])
#     W.append(w_temp);
#     b.append(b_temp)

# output_w = np.random.rand(10,numberOfNeurons[layers-1])
# output_b = np.random.rand(10)
# W.append(output_w)
# b.append(output_b)

# #print(len(W))
# #print(len(b))
# #print(W[0].shape)
# # def randomIntialization(dimx,dimy):
# #   W_temp = np.random.randint(10,size=(dimx,dimy)) # assigning random number between 0-9
# #   b_temp = np.random.randint(10,size=(dimx))
# #   return W_temp, b_temp



# def feedForward(input_data):
    
#    Y= sigmoid(np.dot(W[0],input_data) + b[0])
#    for i in range(1,layers):
#       Y = sigmoid(np.dot(W[i],Y)) + b[i]
  
#    output = sigmoid(np.dot(W[layers],Y)) + b[layers]
#    return output




# output = feedForward(x_trainFlat[0])
# outputSoftmax = softmax(output)
# #print(output.shape)
# print(outputSoftmax)



In [26]:
numberOfNeurons =[] 
for i in range(layers):
  temp = int(input("number of neurons:"))
  numberOfNeurons.append(temp)
def Initalize_Wb():
  #layers = int(input("enter number of Hidden layers:"))
  #layers = int(layers)
 # numberOfNeurons =[]               # number of neurons at each Hidden Layer
  W = []                            #store the Weight matrix at each layer
  b = []                            #store the bias vector at each layer
  for i in range(layers):                       
    #randomNumber = np.random.randint(64,256)
   # numberOfNeurons.append(randomNumber)
    if( i== 0):
      w_temp =np.random.rand(numberOfNeurons[i],784)-0.5
      b_temp = np.random.rand(numberOfNeurons[i],1)-0.5
      W.append(w_temp)
      b.append(b_temp)
    else:
      w_temp = np.random.rand(numberOfNeurons[i],numberOfNeurons[i-1])-0.5
      b_temp = np.random.rand(numberOfNeurons[i],1)-0.5
      W.append(w_temp);
      b.append(b_temp)

  print(numberOfNeurons)
  output_w = np.random.rand(10,numberOfNeurons[layers-1])-0.5
  output_b = np.random.rand(10,1)-0.5
  W.append(output_w)
  b.append(output_b)
  # print(len(W))
  # print(len(b))
  # print(W[0].shape)
  # print(W[1].shape)
  # print(W[2].shape)
  # print(b[0].shape)
  # print(b[1].shape)
  # print(b[2].shape)

  return W,b



def feedForward(input_data,W,b):
  
   output =[]
   temp =[]
   A =[]
  #  print("hello",b[0].shape)
  #  print(b[0].reshape(-1,1).shape)
   Y =np.dot(W[0],input_data) + b[0]
   temp.append(Y)
   Y= ReLU(Y)
   A.append(Y)
   for i in range(1,layers):
      Y =np.dot(W[i],Y) + b[i]
      temp.append(Y)
      Y=ReLU(Y)
      A.append(Y)
   temp2=np.dot(W[layers],Y) + b[layers]
   temp.append(temp2)
   output=(softmax1(ReLU(temp2)))
   #print("softmaxt",output[:,1])
   return output,temp,A






number of neurons:128
number of neurons:64


In [27]:
def find_Actuall_Y():
  X,Y = x_trainFlat.shape
  # print(X)
  Y_actual=[]
  for i in range(X):
    tempX =x_trainFlat[i]
    tempY = y_train[i]
    vector = np.zeros(10)             # creating a vector of size 10 and assigning '1' to the correct index of trainFlat[i]
    vector[tempY] =1
    Y_actual.append(vector)
    # #outputY=softmax(feedForward(x_trainFlat[i]))
    # Y_predicted.append(outputY)
    # loss = -np.mean(np.sum(Y_actual * np.log(Y_predicted),axis =1))          #crossEntropy loss Caluclation
  return Y_actual


Y_actual = find_Actuall_Y()
Y_actual = np.array(Y_actual)
Y_actual = Y_actual.T
print(Y_actual.shape)



# Assuming Y_predicted and Y_actual are 10x60000 arrays
def cross_entropy_loss(Y_actual, Y_predicted):
    # Clip predicted values to avoid log(0) numerical instability
    Y_predicted = np.clip(Y_predicted, 1e-7, 1 - 1e-7)
    
    # Compute cross-entropy loss
    N = Y_actual.shape[1] # number of samples
    loss = -1/N * np.sum(Y_actual * np.log(Y_predicted))
    return loss

# error = cross_entropy_loss(Y_actual, Y_predicted)
# print(error)




(10, 60000)


In [28]:
#Backpropogation Function

def backpropagation(X, Y_actual, Y_predicted, Intermediate_Activation,A,W,b):
    dW = [None] * (len(W)) # gradient of weight matrix at each layer
    db = [None] * (len(b)) # gradient of bias vector at each layer
    
    # Compute derivative of loss with respect to output
    dL_dZ = Y_predicted - Y_actual
    
    # Compute gradients for output layer
   #dW[-1] = 1/X.shape[0] * np.dot(dL_dZ, Intermediate_Activation[-1].T)
    dW[-1] = 1/X.shape[0] * np.dot(dL_dZ, A[-1].T)
    db[-1] = 1/X.shape[0] * np.sum(dL_dZ, axis=1, keepdims=True)
   # print(dL_dZ.shape)
    #print(db[-1].shape)
    
    # Backpropagate gradients through hidden layers
    for l in reversed(range(1, len(W)-1)):
        dL_dY = np.dot(W[l+1].T, dL_dZ)
        # print(dL_dY.shape)
        # print(Intermediate_Activation[l].shape)
        # zy= sigmoid_diff(Intermediate_Activation[l-1])
        # print(zy.shape)
        dL_dZ = dL_dY * ReLU_deriv(Intermediate_Activation[l])
        dW[l] = 1/X.shape[0] * np.dot(dL_dZ, Intermediate_Activation[l-1].T)
        db[l] = 1/X.shape[0] * np.sum(dL_dZ, axis=1, keepdims=True)

    
    # Compute gradients for input layer
    dL_dY = np.dot(W[1].T, dL_dZ)
    dL_dZ = dL_dY * ReLU_deriv(Intermediate_Activation[0])
    dW[0] = 1/X.shape[0] * np.dot(dL_dZ, X)
    db[0] = 1/X.shape[0] * np.sum(dL_dZ, axis=1, keepdims=True)
    # print("insside update",len(db))
    # print(db[0].shape)
    # print(db[1].shape)
    # print(db[2].shape)
    return dW, db

# dW,db = backpropagation(x_trainFlat,Y_actual,Y_predicted,Intermediate_Activation)
# print(dW[0].shape,db[0].shape)
# print(dW[1].shape,db[1].shape)
# print(dW[2].shape,db[2].shape)

In [29]:
def Update(W,b,dW,db,learningRate):

  for i in range (len(W)):
    W[i] = W[i] -learningRate*dW[i]
   # print("before update",b[i].shape,db[i].shape)
    b[i] = b[i] -learningRate* db[i]
    #print("after update",b[i].shape, W[i].shape)
  
  return W,b


#W,b=Update(W,b,dW,db,0.1)


In [30]:

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size




In [31]:
def gradient_descent(x_trainFlat,Y_actual,y_train,iteration,learning_rate):
    W,b = Initalize_Wb()
    print(len(W),len(b))
    for i in range(iteration):
        Y_predicted, Intermediate_Activation, A = feedForward(x_trainFlat.T,W,b)
        dW, db = backpropagation(x_trainFlat,Y_actual,Y_predicted,Intermediate_Activation,A,W,b)
        # print("x",len(b),b[0].shape,b[1].shape,b[2].shape)
        W,b = Update(W,b,dW,db,learning_rate)
        #print("len of b",len(b))
        if i % 10 == 0:
            print("iteration:", i)
           # y_pred = get_prediction(Y_predicted)
            #print("Ypredicted",Y_predicted[:,1])
            #print("y_actual",Y_actual[:,1])
            #acuracy = getAccuracy(Y_predicted, Y_actual)
            predictions = get_predictions(Y_predicted)
            print("Accuracy:", get_accuracy(predictions,y_train)*100)
    return W,b
     

# W,b = gradient_descent(x_trainFlat, Y_actual,y_train,1000, 0.1)

In [32]:
def stochastic_gradient_descent(x_trainFlat, Y_actual, y_train, iteration, learning_rate, batch_size):
    W, b = Initalize_Wb()
    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]
        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]
            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)
            dW_batch, db_batch = backpropagation(x_batch, Y_actual_batch, Y_predicted_batch, Intermediate_Activation_batch, A_batch, W, b)
            # Update the parameters using the batch gradient
            W, b = Update(W, b, dW_batch, db_batch, learning_rate)
        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    return W, b


#W,b = stochastic_gradient_descent(x_trainFlat,Y_actual,y_train,100,0.1,64)

In [33]:
def momentum_gradient_descent(x_trainFlat, Y_actual, y_train, iteration, learning_rate, batch_size, momentum):
    W, b = Initalize_Wb()
    # initialize velocities to zero
    v_dW = [np.zeros_like(w) for w in W]
    v_db = [np.zeros_like(b) for b in b]

    # print(len(v_dW))
    # print(len(v_db))
    
    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]
        
        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]
            
            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)
            dW_batch, db_batch = backpropagation(x_batch, Y_actual_batch, Y_predicted_batch, Intermediate_Activation_batch, A_batch, W, b)
            
            # Update velocities
            v_dW = [momentum * v_dw + (1-momentum) * dw for v_dw, dw in zip(v_dW, dW_batch)]
            v_db = [momentum * v_db + (1-momentum) * db for v_db, db in zip(v_db, db_batch)]
            
            # Update the parameters using the velocity
            W, b = Update(W, b, v_dW, v_db, learning_rate)
            
        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    
    return W, b
#W, b = momentum_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=1000, learning_rate=0.1,batch_size=64, momentum=0.9)

In [34]:
def nesterov_gradient_descent(x_trainFlat, Y_actual, y_train, iteration, learning_rate, momentum,batch_size):
    W, b = Initalize_Wb()
    # initialize velocities to zero
    v_dW = [np.zeros_like(w) for w in W]
    v_db = [np.zeros_like(b) for b in b]

    # print(len(v_dW))
    # print(len(v_db))
    
    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]
        
        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]
            
            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)

            # Compute the gradients at the lookahead position
            W_lookahead = [w - momentum * v_dw for w, v_dw in zip(W, v_dW)]
            b_lookahead = [b - momentum * v_db for b, v_db in zip(b, v_db)]
            Y_predicted_lookahead, _, _ = feedForward(x_batch.T, W_lookahead, b_lookahead)
            dW_batch_lookahead, db_batch_lookahead = backpropagation(x_batch, Y_actual_batch, Y_predicted_lookahead, Intermediate_Activation_batch, A_batch, W_lookahead, b_lookahead)
            
            # Update velocities
            v_dW = [momentum * v_dw + (1-momentum) * dw for v_dw, dw in zip(v_dW, dW_batch_lookahead)]
            v_db = [momentum * v_db + (1-momentum) * db for v_db, db in zip(v_db, db_batch_lookahead)]
            
            # Update the parameters using the velocity
            W, b = Update(W, b, v_dW, v_db, learning_rate)
            
        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    
    return W, b


In [35]:
def rmsprop(x_trainFlat, Y_actual, y_train, iteration, learning_rate, batch_size, beta,epsilon):
    W, b = Initalize_Wb()
    # initialize accumulated gradients to zero
    s_dW = [np.zeros_like(w) for w in W]
    s_db = [np.zeros_like(b) for b in b]

    # set a small constant to avoid division by zero
    #epsilon = 1e-8
    
    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]
        
        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]
            
            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)
            dW_batch, db_batch = backpropagation(x_batch, Y_actual_batch, Y_predicted_batch, Intermediate_Activation_batch, A_batch, W, b)
            
            # Accumulate the squared gradients
            s_dW = [beta * s_dw + (1-beta) * dw**2 for s_dw, dw in zip(s_dW, dW_batch)]
            s_db = [beta * s_db + (1-beta) * db**2 for s_db, db in zip(s_db, db_batch)]
            
            # Update the parameters using the accumulated gradients
            W = [w - learning_rate * dw / np.sqrt(s_dw + epsilon) for w, dw, s_dw in zip(W, dW_batch, s_dW)]
            b = [b - learning_rate * db / np.sqrt(s_db + epsilon) for b, db, s_db in zip(b, db_batch, s_db)]
            
        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    
    return W, b


In [36]:
def adam(x_trainFlat, Y_actual, y_train, iteration, learning_rate, batch_size, beta1, beta2, epsilon):
    W, b = Initalize_Wb()
    # initialize velocities and squared gradients to zero
    v_dW = [np.zeros_like(w) for w in W]
    v_db = [np.zeros_like(b) for b in b]
    s_dW = [np.zeros_like(w) for w in W]
    s_db = [np.zeros_like(b) for b in b]

    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]

        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]

            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)
            dW_batch, db_batch = backpropagation(x_batch, Y_actual_batch, Y_predicted_batch, Intermediate_Activation_batch, A_batch, W, b)

            # Update velocities and squared gradients
            v_dW = [beta1 * v_dw + (1 - beta1) * dw for v_dw, dw in zip(v_dW, dW_batch)]
            v_db = [beta1 * v_db + (1 - beta1) * db for v_db, db in zip(v_db, db_batch)]
            s_dW = [beta2 * s_dw + (1 - beta2) * np.square(dw) for s_dw, dw in zip(s_dW, dW_batch)]
            s_db = [beta2 * s_db + (1 - beta2) * np.square(db) for s_db, db in zip(s_db, db_batch)]

            # Bias correction for velocities and squared gradients
            v_dW_corrected = [v_dw / (1 - beta1**(i+1)) for i, v_dw in enumerate(v_dW)]
            v_db_corrected = [v_db / (1 - beta1**(i+1)) for i, v_db in enumerate(v_db)]
            s_dW_corrected = [s_dw / (1 - beta2**(i+1)) for i, s_dw in enumerate(s_dW)]
            s_db_corrected = [s_db / (1 - beta2**(i+1)) for i, s_db in enumerate(s_db)]

            # Update the parameters
            W, b = Update(W, b, [(learning_rate * v_dW_corrected[i]) / (np.sqrt(s_dW_corrected[i]) + epsilon) for i in range(len(W))], [(learning_rate * v_db_corrected[i]) / (np.sqrt(s_db_corrected[i]) + epsilon) for i in range(len(b))],learning_rate)

        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    
    return W, b


In [37]:
def nadam(x_trainFlat, Y_actual, y_train, iteration, learning_rate, batch_size, beta1, beta2, epsilon):
    W, b = Initalize_Wb()
    # initialize velocities and squared gradients to zero
    v_dW = [np.zeros_like(w) for w in W]
    v_db = [np.zeros_like(b) for b in b]
    s_dW = [np.zeros_like(w) for w in W]
    s_db = [np.zeros_like(b) for b in b]

    # initialize the bias correction terms for velocities
    m_dW = [np.zeros_like(w) for w in W]
    m_db = [np.zeros_like(b) for b in b]

    for i in range(iteration):
        # Randomly shuffle the training data and split it into batches
        idx = np.random.permutation(len(x_trainFlat))
        x_trainFlat_shuffled = x_trainFlat[idx]
        Y_actual_shuffled = Y_actual[:, idx]
        y_train_shuffled = np.array(y_train)[idx]

        for j in range(0, len(x_trainFlat), batch_size):
            # Select a batch of training examples
            x_batch = x_trainFlat_shuffled[j:j+batch_size]
            Y_actual_batch = Y_actual_shuffled[:, j:j+batch_size]
            y_train_batch = y_train_shuffled[j:j+batch_size]

            # Compute the forward pass and backpropagation for the batch
            Y_predicted_batch, Intermediate_Activation_batch, A_batch = feedForward(x_batch.T, W, b)
            dW_batch, db_batch = backpropagation(x_batch, Y_actual_batch, Y_predicted_batch, Intermediate_Activation_batch, A_batch, W, b)

            # Update velocities and squared gradients
            v_dW = [beta1 * v_dw + (1 - beta1) * dw for v_dw, dw in zip(v_dW, dW_batch)]
            v_db = [beta1 * v_db + (1 - beta1) * db for v_db, db in zip(v_db, db_batch)]
            s_dW = [beta2 * s_dw + (1 - beta2) * np.square(dw) for s_dw, dw in zip(s_dW, dW_batch)]
            s_db = [beta2 * s_db + (1 - beta2) * np.square(db) for s_db, db in zip(s_db, db_batch)]

            # Bias correction for velocities and squared gradients
            v_dW_corrected = [v_dw / (1 - beta1**(i+1)) for i, v_dw in enumerate(v_dW)]
            v_db_corrected = [v_db / (1 - beta1**(i+1)) for i, v_db in enumerate(v_db)]
            s_dW_corrected = [s_dw / (1 - beta2**(i+1)) for i, s_dw in enumerate(s_dW)]
            s_db_corrected = [s_db / (1 - beta2**(i+1)) for i, s_db in enumerate(s_db)]

            # Compute the Nesterov momentum update
            m_dW = [(beta1 * v_dW_corrected[i] + (1 - beta1) * dw) / (1 - beta1**(i+1)) for i, dw in enumerate(dW_batch)]
            m_db = [(beta1 * v_db_corrected[i] + (1 - beta1) * db) / (1 - beta1**(i+1)) for i, db in enumerate(db_batch)]

            # Compute the update for
            m_dW = [(beta1 * v_dW_corrected[i] + (1 - beta1) * dw) / (1 - beta1**(i+1)) for i, dw in enumerate(dW_batch)]
            m_db = [(beta1 * v_db_corrected[i] + (1 - beta1) * db) / (1 - beta1**(i+1)) for i, db in enumerate(db_batch)]
            m_dW_corrected = [(beta1 * v_dW_corrected[i] + (1 - beta1) * dw) / (1 - beta1**(i+1)) for i, dw in enumerate(m_dW)]
            m_db_corrected = [(beta1 * v_db_corrected[i] + (1 - beta1) * db) / (1 - beta1**(i+1)) for i, db in enumerate(m_db)]
            v_dW_corrected = [(beta2 * v_dW_corrected[i] + (1 - beta2) * np.square(dw)) for i, dw in enumerate(dW_batch)]
            v_db_corrected = [(beta2 * v_db_corrected[i] + (1 - beta2) * np.square(db)) for i, db in enumerate(db_batch)]
            v_dW_corrected = [v_dW_corrected[i] / (1 - beta2**(i+1)) for i in range(len(v_dW_corrected))]
            v_db_corrected = [v_db_corrected[i] / (1 - beta2**(i+1)) for i in range(len(v_db_corrected))]
            W, b = Update(W, b, [((learning_rate * m_dW_corrected[i]) / (np.sqrt(v_dW_corrected[i]) + epsilon)) if np.greater_equal(v_dW_corrected[i], 0) else ((learning_rate * m_dW_corrected[i]) / (np.sqrt(abs(v_dW_corrected[i])) + epsilon)) for i in range(len(W))], [((learning_rate * m_db_corrected[i]) / (np.sqrt(v_db_corrected[i]) + epsilon)) if v_db_corrected[i] >= 0 else ((learning_rate * m_db_corrected[i]) / (np.sqrt(abs(v_db_corrected[i])) + epsilon)) for i in range(len(b))],learning_rate)


        if i % 10 == 0:
            # Compute the accuracy on the entire training set
            Y_predicted, _, _ = feedForward(x_trainFlat.T, W, b)
            predictions = get_predictions(Y_predicted)
            accuracy = get_accuracy(predictions, y_train) * 100
            print(f"Iteration {i}: accuracy = {accuracy:.2f}%")
    return W,b


In [38]:
def prediction_Test(input_data,W,b):
  Y_predicted, _, _ = feedForward(input_data.T, W, b)
  predictions = get_predictions(Y_predicted)
  accuracy = get_accuracy(predictions, y_test) * 100
  print(f"Test_Accuracy = {accuracy:.2f}%")




In [39]:
# user_input = input("Enter A for gradient descent, B for stochastic gradient descent, C for momentum gradient descent, or D for Nesterov gradient descent: ")

# if user_input == "A":
#     W,b =gradient_descent(x_trainFlat, Y_actual, y_train, iteration=50, learning_rate=0.1)
#     prediction_Test(x_testFlat,W,b)
# elif user_input == "B":
#     W,b =stochastic_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=60, learning_rate=0.1, batch_size=64)
#     prediction_Test(x_testFlat,W,b)
# elif user_input == "C":
#     W,b = momentum_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=50, learning_rate=0.1, batch_size=64, momentum=0.9)
#     prediction_Test(x_testFlat,W,b)
# elif user_input == "D":
    
    
# elif user_input == "E":
#     W,b = rmsprop(x_trainFlat, Y_actual, y_train, iteration=50, learning_rate=0.01, batch_size=64, decay_rate=0.9, epsilon=1e-8)


# else:
#     print("Invalid input. Please enter A, B, C, or D.")

In [ ]:
print("GD")
W,b =gradient_descent(x_trainFlat, Y_actual, y_train, iteration=100, learning_rate=0.1)
prediction_Test(x_testFlat,W,b)
print("sGD")
W,b =stochastic_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=100,learning_rate=0.1, batch_size=64)
prediction_Test(x_testFlat,W,b)
print("MGD")
W,b = momentum_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=100, learning_rate=0.1, batch_size=64, momentum=0.9)
prediction_Test(x_testFlat,W,b)
print("NGD")
W,b = nesterov_gradient_descent(x_trainFlat, Y_actual, y_train, iteration=50, learning_rate=0.1, momentum=0.9, batch_size=64)
prediction_Test(x_testFlat,W,b)
print("rms")
W,b = rmsprop(x_trainFlat, Y_actual, y_train, iteration=50, learning_rate=0.1, batch_size=64, beta=0.9, epsilon=1e-2)
prediction_Test(x_testFlat,W,b)
W,b = adam(x_trainFlat, Y_actual, y_train, iteration=500, learning_rate=0.1, batch_size=64, beta1=0.9, beta2=0.999, epsilon=1e-8)
prediction_Test(x_testFlat,W,b)
# Example usage of nadam() function
# W,b= nadam(x_trainFlat, Y_actual, y_train, iteration=100, learning_rate=0.01, batch_size=32, beta1=0.9, beta2=0.999, epsilon=1e-8)
# prediction_Test(x_testFlat,W,b)


GD
[128, 64]
3 3
iteration: 0
[4 4 4 ... 9 4 3] [9 0 0 ... 3 0 5]
Accuracy: 9.961666666666668
iteration: 10
[9 0 1 ... 0 0 8] [9 0 0 ... 3 0 5]
Accuracy: 56.64
iteration: 20
[9 0 1 ... 3 0 8] [9 0 0 ... 3 0 5]
Accuracy: 65.48666666666666
iteration: 30
[9 0 3 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 67.36999999999999
iteration: 40
[9 0 3 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 69.74666666666667
iteration: 50
[9 0 3 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 71.17999999999999
iteration: 60
[9 0 1 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 72.33500000000001
iteration: 70
[9 0 1 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 73.16666666666667
iteration: 80
[9 0 1 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 73.87666666666667
iteration: 90
[9 0 1 ... 3 0 5] [9 0 0 ... 3 0 5]
Accuracy: 74.52166666666666
[9 2 1 ... 8 1 9] [9 2 1 ... 8 1 5]
Test_Accuracy = 74.10%
sGD
[128, 64]
[9 0 0 ... 3 0 5] [9 0 0 ... 3 0 5]
Iteration 0: accuracy = 81.79%
[9 0 0 ... 3 0 5] [9 0 0 ... 3 0 5]
Iteration 10: accuracy = 88.74%
[9 0 0 .